Add fix-v8-tnode-incomplete-type patch for GCC 14/15
After the worker_inspector cstdint fix, the unstable build gets further
and now fails in deps/v8/src/codegen/tnode.h:250 with:

  /usr/include/c++/15/type_traits:1567:30: error: invalid use of
  incomplete type 'class v8::internal::Cell'
  ../deps/v8/src/codegen/tnode.h:250:72: error: 'value' is not a member
  of 'std::is_convertible<v8::internal::Cell, v8::internal::Object>'

GCC 15's libstdc++ requires types to be complete when
std::is_convertible is instantiated. code-stub-assembler.h included
<functional> (which triggers the instantiation) before the object
headers (cell.h, js-generator.h, js-promise.h) that complete the
forward-declared types used as TNode template arguments.

Move those three object headers above <functional> so the types are
complete when the template traits are evaluated.